[package]
name = "tree"
description = "A program to recursively list the contents of a folder in a tree-like manner."
version = "0.1.0"
authors = ["vzwGrey <vzwgrey@gmail.com>"]
license = "MIT"
edition = "2018"
publish = false

[dependencies]
